name: Build
on:
  pull_request:
  push:
    branches:
      - v3.x
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rlespinasse/github-slug-action@v3.x
      - name: Build docker image
        run: make build
        env:
          DOCKER_IMAGE: ${{ github.repository }}:${{ env.GITHUB_REF_SLUG }}
      - uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.1.2
          branches: |
            [
              'v2.x',
              'v3.x'
            ]
          extra_plugins: |
            @semantic-release/changelog@5.0.1
            @semantic-release/git@9.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
